<!DOCTYPE html>
<html class='borderbox'>

  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0,
  maximum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <link rel="alternate" hreflang="x-default" href="" />

  <!-- google verify and baidu verify -->
  <meta name="google-site-verification" content="joolptd8YEk3DYbnLzqB6hkhqyM0_UkEvB4XS6-Vfgc" />
  <meta name="baidu-site-verification" content="9nNaof1vhh" />

  <title>PHP 的错误和异常处理机制</title>
  <meta name="description" content="原先的 PHP 只有错误没有异常。看一些老的文档你能看到不少错误输出是直接 echo html 标签的。而现代一点的框架早已经包裹好了一切，直接抛出异常就可以有比较漂亮的错误显示页面，比如 rails 的 better errors。当然，PHP 的现代框架也已经做的不错了，比如 laravel。然而我司目前还是用 codeigniter 2，它的错误和异常处理还比较简陋。借着升级到 PHP7 的契机梳理了一下 PHP 的错误和异常处理的机制。

">
  <meta name="keywords" content="php,error,exception,throwable">
  <link rel="canonical" href="http://wulfric.me/2017/08/php-error-exception/">
  <link type="text/css" rel="stylesheet" href="/assets/app.css" media=screen>
  
</head>


  <body>
    <div class='content'>
      <h1 class='header-header'>
  
  <a class="site-title" href="/">
    <span id='titile-first-part'>STORM</span><span id='titile-last-part'>SPIRIT </span>
  </a>
</h1>
<nav class='header-nav'>
  <a class="page-link" href="/">HOME</a>
  /
  <a class="page-link" href="/archive/">ARCHIVE</a>
  /
  <a class="page-link" href="/feed.xml">FEED</a>
  /
  <a class="page-link" href="/about/">ABOUT</a>
</nav>


      <div class='main'>
        <div class="post typo">

  <header class="post-header clearfix">
    <div class='date pull-left clearfix'>
      <div class='day-month pull-left'>
        <div class='day'>04</div>
        <div class='month'>AUG</div>
      </div>
      <div class='year pull-left'>2017</div>
    </div>
    <h1 class="post-title">PHP 的错误和异常处理机制</h1>
  </header>

  
<blockquote id='by-nc-nd'>
  声明: 本文采用
  <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh" rel="nofollow" target="_blank" title="姓名标示-非商业性-禁止改作4.0国际">CC BY-NC-ND 4.0</a>
  授权。
</blockquote>




  <article class="post-content">
    <p>原先的 PHP 只有错误没有异常。看一些老的文档你能看到不少错误输出是直接 echo html 标签的。而现代一点的框架早已经包裹好了一切，直接抛出异常就可以有比较漂亮的错误显示页面，比如 rails 的 <a href="https://github.com/charliesome/better_errors">better errors</a>。当然，PHP 的现代框架也已经做的不错了，比如 laravel。然而我司目前还是用 codeigniter 2，它的错误和异常处理还比较简陋。借着升级到 PHP7 的契机梳理了一下 PHP 的错误和异常处理的机制。</p>

<h2 id="php-的错误和异常">PHP 的错误和异常</h2>

<p>PHP5 已经实现了异常的处理，这和其他语言差别不大，无非就是 try, catch, uncaught，按下不表，先说错误。</p>

<h3 id="php-的错误">PHP 的错误</h3>

<p>除了异常 PHP5 常见的就是抛出错误。你可以在官方<a href="http://php.net/manual/zh/errorfunc.constants.php">文档</a>找到所有的错误的定义，这些错误可以大致分为 WARNING, ERROR(fatal error), NOTICE 等<sup id="fnref:1"><a href="#fn:1" class="footnote">1</a></sup>。<a href="http://www.cnblogs.com/yjf512/p/5314345.html">PHP的错误机制总结</a>一文中给出了每种错误出现的场景。</p>

<blockquote>
  <p>E_DEPRECATED(8192)  运行时通知,启用后将会对在未来版本中可能无法正常工作的代码给出警告。</p>

  <p>E_USER_DEPRECATED(16384)  是由用户自己在代码中使用PHP函数 trigger_error() 来产生的</p>
</blockquote>

<blockquote>
  <p>E_NOTICE(8)  运行时通知。表示脚本遇到可能会表现为错误的情况</p>

  <p>E_USER_NOTICE(1024)  是用户自己在代码中使用PHP的trigger_error() 函数来产生的通知信息</p>
</blockquote>

<blockquote>
  <p>E_WARNING(2)  运行时警告 (非致命错误)</p>

  <p>E_USER_WARNING(512)  用户自己在代码中使用PHP的 trigger_error() 函数来产生的</p>

  <p>E_CORE_WARNING(32)  PHP初始化启动过程中由PHP引擎核心产生的警告</p>

  <p>E_COMPILE_WARNING(128)  Zend脚本引擎产生编译时警告</p>
</blockquote>

<blockquote>
  <p>E_ERROR(1)  致命的运行时错误</p>

  <p>E_USER_ERROR(256)  用户自己在代码中使用PHP的 trigger_error()函数来产生的</p>

  <p>E_CORE_ERROR(16)  在PHP初始化启动过程中由PHP引擎核心产生的致命错误</p>

  <p>E_COMPILE_ERROR(64)  Zend脚本引擎产生的致命编译时错误</p>
</blockquote>

<blockquote>
  <p>E_PARSE(4)  编译时语法解析错误。解析错误仅仅由分析器产生</p>
</blockquote>

<blockquote>
  <p>E_STRICT(2048)  启用 PHP 对代码的修改建议，以确保代码具有最佳的互操作性和向前兼容性</p>
</blockquote>

<blockquote>
  <p>E_RECOVERABLE_ERROR(4096)  可被捕捉的致命错误。 它表示发生了一个可能非常危险的错误，但是还没有导致PHP引擎处于不稳定的状态。 如果该错误没有被用户自定义句柄捕获 (参见 set_error_handler() )，将成为一个 E_ERROR 　从而脚本会终止运行。</p>
</blockquote>

<blockquote>
  <p>E_ALL(30719) 所有错误和警告信息(手册上说不包含E_STRICT, 经过测试其实是包含E_STRICT的)。</p>
</blockquote>

<p>常见的有：</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="c1">// E_ERROR
</span><span class="nx">nonexist</span><span class="p">();</span> <span class="c1">// PHP Fatal error:  Call to undefined function nonexist()
</span><span class="k">throw</span> <span class="k">new</span> <span class="nx">Exception</span><span class="p">(</span><span class="s1">''</span><span class="p">);</span> <span class="c1">// 未捕获异常也是 fatal error
</span>
<span class="c1">// E_NOTICE
</span><span class="nv">$a</span> <span class="o">=</span> <span class="nv">$b</span><span class="p">;</span> <span class="c1">//  PHP Notice:  Undefined variable
</span><span class="nv">$a</span> <span class="o">=</span> <span class="p">[];</span> <span class="nv">$a</span><span class="p">[</span><span class="mi">2</span><span class="p">];</span> <span class="c1">// PHP Notice:  Undefined offset: 2
</span>
<span class="c1">// E_WARNNING
</span><span class="k">require</span> <span class="s1">'nonexist.php'</span> <span class="c1">// warning and fatal error
</span></code></pre></div></div>

<p>由于历史原因，这个老旧的 ci2 框架有不少不合理的地方，比如会读取不存在的 log 文件；我们对 PHP 也有一些不规范的使用，比如：</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="nv">$req</span> <span class="o">=</span> <span class="p">[];</span>
<span class="nv">$user_id</span> <span class="o">=</span> <span class="nv">$req</span><span class="p">[</span><span class="s1">'user_id'</span><span class="p">];</span> <span class="c1">// PHP error:  Undefined offset
</span><span class="k">if</span> <span class="p">(</span><span class="kc">null</span> <span class="o">===</span> <span class="nv">$user_id</span><span class="p">)</span> <span class="p">{</span> <span class="cm">/* do something */</span><span class="p">}</span>
</code></pre></div></div>

<p>我们的代码不少地方较为依赖这种获取不存在 key 得到 null 的表现，而每次这样使用都是会有一个 E_NOTICE 错误的。虽然可以通过 array_exists 来做 if else，但毕竟比较麻烦。PHP7 之后可以通过<a href="http://php.net/manual/zh/book.ds.php">数据结构</a>插件来使用 Map, Set, Vector 等明确的数据结构，从而较好的解决这个问题。</p>

<h3 id="php-对错误的处理">PHP 对错误的处理</h3>

<p>如果没有做任何配置，PHP 的错误是会直接打印出来的。古老的 PHP 应用也确实有这么做的。但现代应用显然不能这样，现代应用的错误应该遵循一下规则<sup id="fnref:2"><a href="#fn:2" class="footnote">2</a></sup>：</p>

<blockquote>
  <p>一定要让 PHP 报告错误；</p>

  <p>在开发环境中要显示错误；</p>

  <p>在生产环境中不能显示错误；</p>

  <p>在开发和生产环境中都要记录错误。</p>
</blockquote>

<p>在生产环境下，错误不能直接打印出来，应该记到 log 文件中，并返回用户一个笼统的错误信息。<a href="http://php.net/manual/zh/function.set-error-handler.php">set_error_handler 函数</a>就是设置用户自定义的错误处理函数，以处理脚本中出现的错误。我们可以在这个函数中将错误信息打到 log 文件中，并统一返回错误信息。</p>

<p>本来这个函数是搭配 <a href="http://php.net/manual/zh/function.trigger-error.php">trigger_error 函数</a>使用的。用户通过 trigger_error 产生 error，然后用 error_handler 来处理错误。只是在这种场景下往往「异常」更好用，所以这么用的并不多。</p>

<p>在前述的系统自带的 16 种错误中，有一部分相当重要的错误并不能被 error_handler 捕获<sup id="fnref:3"><a href="#fn:3" class="footnote">3</a></sup>：</p>

<blockquote>
  <p>以下级别的错误不能由用户定义的函数来处理： E_ERROR、 E_PARSE、 E_CORE_ERROR、 E_CORE_WARNING、 E_COMPILE_ERROR、E_COMPILE_WARNING，和在调用 set_error_handler() 函数所在文件中产生的大多数 E_STRICT。</p>
</blockquote>

<p>这些错误将无法记录下来，同时也不方便统一处理<sup id="fnref:4"><a href="#fn:4" class="footnote">4</a></sup>。在 PHP7 之前的 PHP 版本一个很大的痛点就是：发生了 E_ERROR 错误，无法捕获，导致数据库的事务无法回滚造成数据不一致<sup id="fnref:5"><a href="#fn:5" class="footnote">5</a></sup>。</p>

<p>另外一个需要注意的是， error_handler 处理完毕，脚本将会继续执行发生错误的后一行。在某些情况下，你可能希望遇到某些错误可以中断脚本的执行。在<a href="http://php.net/manual/zh/function.set-error-handler.php">官方文档</a>中已说明，</p>

<blockquote>
  <p>同时注意，在需要时你有责任使用 <a href="http://php.net/manual/zh/function.die.php">die()</a>。 如果错误处理程序返回了，脚本将会继续执行发生错误的后一行。</p>
</blockquote>

<p>也就是说，某些情况下，我们处理完 E_WARNING 之后，需要及时退出脚本（即 die() 或者 exit()）。</p>

<h3 id="php-异常">PHP 异常</h3>

<p><a href="https://www.wikiwand.com/zh-hans/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86">异常</a>是对程序错误的一种优秀的处理方式，较于错误，异常的优点是默认打印调用栈，便于调试，可控等，可以参考一下鸟哥的文章<a href="http://www.laruence.com/2012/02/02/2515.html">我们什么时候应该使用异常</a>，清晰的点明了错误码和异常的优缺点。</p>

<p>对异常的处理也要遵循前述的错误处理规则<sup id="fnref:2:1"><a href="#fn:2" class="footnote">2</a></sup>。在我们的日常开发中，不可能保证可以 catch 所有的异常，而未被 catch 的异常将以 fatal error 的形式中断脚本的执行并输出错误信息。所以要借助 <a href="http://php.net/manual/zh/function.set-exception-handler.php">set_exception_handler</a>，统一处理所有未被 catch 的异常。我们可以像 error_handler 那样，在 exception_handler 中处理 log，将数据库的事务回滚。</p>

<p>前面提到，error_handler 需要在必要的时候手动中断脚本， PHP 文档中给出的一种实践是，在 error_handler 中 throw <a href="http://php.net/manual/en/class.errorexception.php">ErrorException</a>，代码示例如下：</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">function</span> <span class="nf">exception_error_handler</span><span class="p">(</span><span class="nv">$severity</span><span class="p">,</span> <span class="nv">$message</span><span class="p">,</span> <span class="nv">$file</span><span class="p">,</span> <span class="nv">$line</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="p">(</span><span class="nb">error_reporting</span><span class="p">()</span> <span class="o">&amp;</span> <span class="nv">$severity</span><span class="p">))</span> <span class="p">{</span>
        <span class="c1">// This error code is not included in error_reporting
</span>        <span class="k">return</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nx">ErrorException</span><span class="p">(</span><span class="nv">$message</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="nv">$severity</span><span class="p">,</span> <span class="nv">$file</span><span class="p">,</span> <span class="nv">$line</span><span class="p">);</span>
<span class="p">}</span>
<span class="nb">set_error_handler</span><span class="p">(</span><span class="s2">"exception_error_handler"</span><span class="p">);</span>

<span class="cm">/* Trigger exception */</span>
<span class="nb">strpos</span><span class="p">();</span>
</code></pre></div></div>

<p>这样凡是不想忽略的 error，都会以 Uncaught ErrorException 的形式返回并中断脚本。</p>

<h3 id="php-异常机制">PHP 异常机制</h3>

<p>鸟哥通过一个<a href="http://www.laruence.com/2010/08/03/1697.html">例子</a>讲解了 PHP 的异常的处理机制，在这里转述一下。</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">function</span> <span class="nf">onError</span><span class="p">(</span><span class="nv">$errCode</span><span class="p">,</span> <span class="nv">$errMesg</span><span class="p">,</span> <span class="nv">$errFile</span><span class="p">,</span> <span class="nv">$errLine</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">echo</span> <span class="s2">"Error Occurred</span><span class="se">\n</span><span class="s2">"</span><span class="p">;</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nx">Exception</span><span class="p">(</span><span class="nv">$errMesg</span><span class="p">);</span>
<span class="p">}</span>
 
<span class="k">function</span> <span class="nf">onException</span><span class="p">(</span><span class="nv">$e</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">echo</span> <span class="s1">'********exception: '</span> <span class="o">.</span> <span class="nv">$e</span><span class="o">-&gt;</span><span class="na">getMessage</span><span class="p">();</span>
<span class="p">}</span>
 
<span class="nb">set_error_handler</span><span class="p">(</span><span class="s2">"onError"</span><span class="p">);</span>
 
<span class="nb">set_exception_handler</span><span class="p">(</span><span class="s2">"onException"</span><span class="p">);</span>

<span class="k">require</span><span class="p">(</span><span class="s2">"nonexist.php"</span><span class="p">);</span>
</code></pre></div></div>

<p>其运行结果为</p>

<ol>
  <li>Error Occurred</li>
  <li>PHP Fatal error</li>
</ol>

<p>而 onException 并没有执行到，说明在 error_handler 中 throw exception 不会被 exception_handler 截获。</p>

<p>require 不存在的文件会抛出两个错误，</p>

<ol>
  <li>WARNING : 在PHP试图打开这个文件的时候抛出</li>
  <li>E_COMPILE_ERROR : 从PHP打开文件的函数返回失败以后抛出</li>
</ol>

<p>PHP 中的异常处理机制如下：</p>

<p><figure>
          <picture>
            
            
            <img src="http://laruence-wordpress.stor.sinaapp.com/uploads/PHP-exception-cycle.png" alt="" width= height= />
          </picture>
          
        </figure></p>

<p>PHP在遇到 Fatal Error 的时候，会直接 zend_bailout，而 zend_bailout 会导致程序流程直接跳过上面代码段，也可以理解为直接 exit 了(longjmp)，这就导致了 user_exception_handler 没有机会发生作用。</p>

<h3 id="php-错误分类">PHP 错误分类</h3>

<p>综上所述，在 PHP 中，错误和异常可以分为以下 3 个类别：异常，可截获错误，不可截获错误。异常和可截获错误虽然机理不同，但可以当做是同一种处理方式，而不可截获错误是另一种，是一种较为棘手的错误类型。马上将会讲到，PHP7  中的 fatal error 是一种继承自 Throwable 的 Error，是可以被 try catch 住的。通过这一方式 PHP7 解决了这一难题。</p>

<h2 id="php7-的错误和异常">PHP7 的错误和异常</h2>

<p>PHP 7 改变了大多数错误的报告方式。不同于传统（PHP 5）的错误报告机制，现在大多数错误被作为 <strong>Error</strong> 异常抛出（在 PHP7 中，只有 fatal error 和 recoverable error 抛出异常，其他 error 比如 warning 和 notice 的表现不变<sup id="fnref:7"><a href="#fn:7" class="footnote">6</a></sup>）。PHP7 中的 Error 和 Exception 的关系如图<sup id="fnref:7:1"><a href="#fn:7" class="footnote">6</a></sup>：</p>

<div  class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>interface Throwable
    |- Exception implements Throwable
        |- ...
    |- Error implements Throwable
        |- TypeError extends Error
        |- ParseError extends Error
        |- ArithmeticError extends Error
            |- DivisionByZeroError extends ArithmeticError
        |- AssertionError extends Error
</code></pre></div></div>

<p>值得注意的是，Error 类表现上和 Exception 基本一致，可以像 <a href="http://php.net/manual/zh/class.exception.php">Exception</a> 异常一样被第一个匹配的 try / catch 块所捕获，如果没有匹配的 <a href="http://php.net/manual/zh/language.exceptions.php#language.exceptions.catch">catch</a> 块，则调用异常处理函数（事先通过 set_exception_handler() 注册<sup id="fnref:6"><a href="#fn:6" class="footnote">7</a></sup>）进行处理。 如果尚未注册异常处理函数，则按照传统方式处理，被报告为一个致命错误（Fatal Error）。但并非继承自 <a href="http://php.net/manual/zh/class.exception.php">Exception</a> 类（要考虑到和 PHP5 的兼容性），所以不能用 <span class="codespan">catch (Exception $e) { ... }</span> 来捕获，而需要使用 <span class="codespan">catch (Error $e) { ... }</span>，当然，也可以使用 set_exception_handler 来捕获。</p>

<p>但是，用户不能自己定义类实现 Throwable，这是为了保证只有 Exception 和 Error 才可以抛出。</p>

<h3 id="php7-的-error-处理">PHP7 的 ERROR 处理</h3>

<p>PHP7 中的 fatal error 会抛出 Error，且可以被正常 catch 到：</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="nv">$a</span> <span class="o">=</span> <span class="mi">1</span><span class="p">;</span>
<span class="k">try</span> <span class="p">{</span>
  <span class="nv">$a</span><span class="o">-&gt;</span><span class="na">nonexist</span><span class="p">();</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">Error</span> <span class="nv">$e</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// Handle error
</span><span class="p">}</span>
</code></pre></div></div>

<p>也有些错误场景下会抛出更加详细的错误，比如：</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="c1">// TypeError
</span><span class="k">function</span> <span class="nf">test</span><span class="p">(</span><span class="nx">int</span> <span class="nv">$i</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">echo</span> <span class="nv">$i</span><span class="p">;</span>
<span class="p">}</span>
<span class="k">try</span> <span class="p">{</span>
  <span class="nx">test</span><span class="p">(</span><span class="s1">'test'</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">TypeError</span> <span class="nv">$e</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// Handle error
</span><span class="p">}</span>

<span class="c1">// ParseError
</span><span class="k">try</span><span class="p">{</span>
  <span class="k">eval</span><span class="p">(</span><span class="s1">'i=1;'</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">ParseError</span> <span class="nv">$e</span><span class="p">)</span> <span class="p">{</span> 
  <span class="k">echo</span> <span class="nv">$e</span><span class="o">-&gt;</span><span class="na">getMessage</span><span class="p">(),</span> <span class="s2">"</span><span class="se">\n</span><span class="s2">"</span><span class="p">;</span>
<span class="p">}</span>

<span class="c1">// ArithmeticError
</span><span class="k">try</span> <span class="p">{</span>
    <span class="nv">$value</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">&lt;&lt;</span> <span class="o">-</span><span class="mi">1</span><span class="p">;</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">ArithmeticError</span> <span class="nv">$e</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">echo</span> <span class="nv">$e</span><span class="o">-&gt;</span><span class="na">getMessage</span><span class="p">(),</span> <span class="s2">"</span><span class="se">\n</span><span class="s2">"</span><span class="p">;</span>
<span class="p">}</span>

<span class="c1">// DivisionByZeroError
</span><span class="k">try</span> <span class="p">{</span>
    <span class="nv">$value</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">%</span> <span class="mi">0</span><span class="p">;</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">DivisionByZeroError</span> <span class="nv">$e</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">echo</span> <span class="nv">$e</span><span class="o">-&gt;</span><span class="na">getMessage</span><span class="p">(),</span> <span class="s2">"</span><span class="se">\n</span><span class="s2">"</span><span class="p">;</span>
<span class="p">}</span>
</code></pre></div></div>

<h3 id="error-和-exception-的选择">Error 和 Exception 的选择</h3>

<p>当需要自定义处理错误的时候，应该选择继承 Error 还是 Exception 呢？</p>

<p>我们注意到，PHP7 中是将曾经的 fatal error 变成了 Error 抛出，而 fatal error 一般都是一些不需要在运行时处理的错误，这种错误旨在提醒程序员，这里的代码写的有问题，需要修复，而不是逻辑上要 catch 它做某些业务。</p>

<p>因此，绝大多数情况下，我们并不需要继承 Error，甚至 catch Error 也不常见，只在某些需要 log，回滚数据库，清理现场等场合才需要这样做。</p>

<h3 id="对错误和异常的一种实践">对错误和异常的一种实践</h3>

<p>根据以上所述，我们提炼了一个对错误和异常处理较好的实践。</p>

<p>对于业务中不应该出现错误的地方，抛出 InternalException，而不是 Error。</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">class</span> <span class="nc">InternalException</span> <span class="k">extends</span> <span class="nx">Exception</span> <span class="p">{</span> <span class="cm">/*...*/</span> <span class="p">}</span>

<span class="k">function</span> <span class="nf">find</span><span class="p">(</span><span class="nx">Array</span> <span class="nv">$ids</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">if</span> <span class="p">(</span><span class="k">empty</span><span class="p">(</span><span class="nv">$ids</span><span class="p">))</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nx">InternalException</span><span class="p">(</span><span class="s1">'ids should not be empty'</span><span class="p">);</span>
  <span class="p">}</span>
  <span class="o">...</span>
<span class="p">}</span>
</code></pre></div></div>

<p>只在需要清理现场的时候 catch Error。</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">try</span> <span class="p">{</span> <span class="cm">/*...*/</span> <span class="p">}</span>
<span class="k">catch</span> <span class="p">(</span><span class="nx">Throwable</span> <span class="nv">$t</span><span class="p">)</span> <span class="p">{</span>
  <span class="c1">// log, transaction rollback, cleanup...
</span><span class="p">}</span>
</code></pre></div></div>

<p>未捕获的 Error 和 Exception 通过 set_exception_handler 做后续清理和 log。</p>

<p>其他错误仍然通过 set_error_handler 来处理，在处理的时候使用更加明确的 FriendlyErrorType，并抛出 ErrorException 记录调用栈。</p>

<p>FriendlyErrorType：</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">function</span> <span class="nf">FriendlyErrorType</span><span class="p">(</span><span class="nv">$type</span><span class="p">)</span> 
<span class="p">{</span> 
    <span class="k">switch</span><span class="p">(</span><span class="nv">$type</span><span class="p">)</span> 
    <span class="p">{</span> 
        <span class="k">case</span> <span class="k">E_ERROR</span><span class="o">:</span> <span class="c1">// 1 // 
</span>            <span class="k">return</span> <span class="s1">'E_ERROR'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="k">E_WARNING</span><span class="o">:</span> <span class="c1">// 2 // 
</span>            <span class="k">return</span> <span class="s1">'E_WARNING'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="k">E_PARSE</span><span class="o">:</span> <span class="c1">// 4 // 
</span>            <span class="k">return</span> <span class="s1">'E_PARSE'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_NOTICE</span><span class="o">:</span> <span class="c1">// 8 // 
</span>            <span class="k">return</span> <span class="s1">'E_NOTICE'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_CORE_ERROR</span><span class="o">:</span> <span class="c1">// 16 // 
</span>            <span class="k">return</span> <span class="s1">'E_CORE_ERROR'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_CORE_WARNING</span><span class="o">:</span> <span class="c1">// 32 // 
</span>            <span class="k">return</span> <span class="s1">'E_CORE_WARNING'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_COMPILE_ERROR</span><span class="o">:</span> <span class="c1">// 64 // 
</span>            <span class="k">return</span> <span class="s1">'E_COMPILE_ERROR'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_COMPILE_WARNING</span><span class="o">:</span> <span class="c1">// 128 // 
</span>            <span class="k">return</span> <span class="s1">'E_COMPILE_WARNING'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_USER_ERROR</span><span class="o">:</span> <span class="c1">// 256 // 
</span>            <span class="k">return</span> <span class="s1">'E_USER_ERROR'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_USER_WARNING</span><span class="o">:</span> <span class="c1">// 512 // 
</span>            <span class="k">return</span> <span class="s1">'E_USER_WARNING'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_USER_NOTICE</span><span class="o">:</span> <span class="c1">// 1024 // 
</span>            <span class="k">return</span> <span class="s1">'E_USER_NOTICE'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_STRICT</span><span class="o">:</span> <span class="c1">// 2048 // 
</span>            <span class="k">return</span> <span class="s1">'E_STRICT'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_RECOVERABLE_ERROR</span><span class="o">:</span> <span class="c1">// 4096 // 
</span>            <span class="k">return</span> <span class="s1">'E_RECOVERABLE_ERROR'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_DEPRECATED</span><span class="o">:</span> <span class="c1">// 8192 // 
</span>            <span class="k">return</span> <span class="s1">'E_DEPRECATED'</span><span class="p">;</span> 
        <span class="k">case</span> <span class="nx">E_USER_DEPRECATED</span><span class="o">:</span> <span class="c1">// 16384 // 
</span>            <span class="k">return</span> <span class="s1">'E_USER_DEPRECATED'</span><span class="p">;</span> 
    <span class="p">}</span> 
    <span class="k">return</span> <span class="s2">""</span><span class="p">;</span> 
<span class="p">}</span>
</code></pre></div></div>

<p>error_handler:</p>

<div  class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">function</span> <span class="nf">exception_error_handler</span><span class="p">(</span><span class="nv">$severity</span><span class="p">,</span> <span class="nv">$message</span><span class="p">,</span> <span class="nv">$file</span><span class="p">,</span> <span class="nv">$line</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="o">!</span><span class="p">(</span><span class="nb">error_reporting</span><span class="p">()</span> <span class="o">&amp;</span> <span class="nv">$severity</span><span class="p">))</span> <span class="p">{</span>
        <span class="c1">// This error code is not included in error_reporting
</span>        <span class="k">return</span><span class="p">;</span>
    <span class="p">}</span>
 	<span class="nb">log</span> <span class="nx">FriendlyErrorType</span><span class="p">(</span><span class="nv">$severity</span><span class="p">);</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nx">ErrorException</span><span class="p">(</span><span class="nv">$message</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="nv">$severity</span><span class="p">,</span> <span class="nv">$file</span><span class="p">,</span> <span class="nv">$line</span><span class="p">);</span>
<span class="p">}</span>
<span class="nb">set_error_handler</span><span class="p">(</span><span class="s2">"exception_error_handler"</span><span class="p">);</span>
</code></pre></div></div>

<p>PHP 会把所有的错误都交给错误处理程序，甚至包括错误报告设置中排除的错误。因此，我们要检查每个错误代码<span class="codespan">$severity</span>，然后做适当的处理<sup id="fnref:8"><a href="#fn:8" class="footnote">8</a></sup>。</p>

<div class="footnotes">
  <ol>
    <li id="fn:1">
      <p><a href="http://www.jianshu.com/p/1b6004a94eb8">PHP中的错误级别与具体报错信息分类</a> <a href="#fnref:1" class="reversefootnote">&#8617;</a></p>
    </li>
    <li id="fn:2">
      <p><a href="https://book.douban.com/subject/26635862/">modern php</a> 第五章，P115 <a href="#fnref:2" class="reversefootnote">&#8617;</a> <a href="#fnref:2:1" class="reversefootnote">&#8617;<sup>2</sup></a></p>
    </li>
    <li id="fn:3">
      <p>E_ERROR 无法捕获，E_RECOVERABLE_ERROR 可以，后者默认输出 Catachable fatal error <a href="#fnref:3" class="reversefootnote">&#8617;</a></p>
    </li>
    <li id="fn:4">
      <p>fatal error 会记录到 web 服务器的 error.log，这一点需要注意，因为这个 log 的位置往往不是 PHP 应用定义的，而是 web 服务器定义的。 <a href="#fnref:4" class="reversefootnote">&#8617;</a></p>
    </li>
    <li id="fn:5">
      <p>PHP 中还有一个 <a href="http://php.net/manual/zh/function.register-shutdown-function.php">register_shutdown_function</a> 函数，它允许注册一个会在 PHP 中止时执行的函数，这个函数可以捕获 fatal error，毕竟是只要是脚本中断就可以捕获的。ci2 并没有使用这个方法，所以相关问题一直没有得到很好的解决，当时也没有意识到这个函数的存在，升级 PHP7 之后可以通过 catch Error 来解决，便不再需要这样处理了。 <a href="#fnref:5" class="reversefootnote">&#8617;</a></p>
    </li>
    <li id="fn:7">
      <p><a href="https://trowski.com/2015/06/24/throwable-exceptions-and-errors-in-php7/">Throwable Exceptions and Errors in PHP 7</a> <a href="#fnref:7" class="reversefootnote">&#8617;</a> <a href="#fnref:7:1" class="reversefootnote">&#8617;<sup>2</sup></a></p>
    </li>
    <li id="fn:6">
      <p>在 PHP7 中，传入 exception_handler 的参数从 <a href="http://php.net/manual/zh/class.exception.php">Exception</a> 改为 Throwable，这意味着 exception_handler 可以截获 Error。 <a href="#fnref:6" class="reversefootnote">&#8617;</a></p>
    </li>
    <li id="fn:8">
      <p>modern php 第五章，P116 <a href="#fnref:8" class="reversefootnote">&#8617;</a></p>
    </li>
  </ol>
</div>

  </article>

  <div id='additional' class='clearfix'>
    <div id="tags" class='pull-left'>
      <i class='icon-tags'></i>
<!-- php, error, exception, throwable -->

    <a class='tag' href="/tags/php">
      php
    </a>

    <a class='tag' href="/tags/error">
      error
    </a>

    <a class='tag' href="/tags/exception">
      exception
    </a>

    <a class='tag' href="/tags/throwable">
      throwable
    </a>


    </div>
    
      <a class='pull-right' href="#comments" id="get-comment">
        <i class='icon-chat'></i>
        评论
      </a>
    
  </div>

  
    <div id="comments" class="comments-hide">
      <div id="lv-container" data-id="city" data-uid="MTAyMC8yOTYwNC82MTcy">
	<script type="text/javascript">
   (function(d, s) {
       var j, e = d.getElementsByTagName(s)[0];

       if (typeof LivereTower === 'function') { return; }

       j = d.createElement(s);
       j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
       j.async = true;

       e.parentNode.insertBefore(j, e);
   })(document, 'script');
	</script>
<!-- <noscript> 为正常使用来必力评论功能请激活JavaScript</noscript> -->
</div>

    </div>
  

</div>

      </div>

      <footer>
  wulfric © 2013~2019. All rights reserved.
</footer>


    </div>
    <script type="text/javascript" src="/assets/app.js"></script>
    <script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F5df5db8eb71e11a9a0fc1df6ca607529' type='text/javascript'%3E%3C/script%3E"));
</script>
<script>
(function(){
  var bp = document.createElement('script');
  var curProtocol = window.location.protocol.split(':')[0];
  if (curProtocol === 'https') {
    bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';        
  }
  else {
    bp.src = 'http://push.zhanzhang.baidu.com/push.js';
  }
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(bp, s);
})();
</script>

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54608037-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
</script>

  </body>

</html>
